//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bluephase.Data.EF6.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BluephaseEntities : DbContext
    {
        public BluephaseEntities()
            : base("name=BluephaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<ContactDetail> ContactDetails { get; set; }
        public virtual DbSet<CustomerAddress> CustomerAddresses { get; set; }
        public virtual DbSet<CustomerContact> CustomerContacts { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<DocumentAudit> DocumentAudits { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<DocumentType> DocumentTypes { get; set; }
        public virtual DbSet<DocumentVersion> DocumentVersions { get; set; }
        public virtual DbSet<EmployeeGroup> EmployeeGroups { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<MaterialForm> MaterialForms { get; set; }
        public virtual DbSet<Material> Materials { get; set; }
        public virtual DbSet<MaterialSupplier> MaterialSuppliers { get; set; }
        public virtual DbSet<NonConformancy> NonConformancies { get; set; }
        public virtual DbSet<PartDocument> PartDocuments { get; set; }
        public virtual DbSet<Part> Parts { get; set; }
        public virtual DbSet<PartVersionDocument> PartVersionDocuments { get; set; }
        public virtual DbSet<PartVersionMaterial> PartVersionMaterials { get; set; }
        public virtual DbSet<PartVersion> PartVersions { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<PersonAddress> PersonAddresses { get; set; }
        public virtual DbSet<PersonContactDetail> PersonContactDetails { get; set; }
        public virtual DbSet<ProductionCentre> ProductionCentres { get; set; }
        public virtual DbSet<ProductionCentreType> ProductionCentreTypes { get; set; }
        public virtual DbSet<ProductionOperationDocument> ProductionOperationDocuments { get; set; }
        public virtual DbSet<ProductionOperationMaterial> ProductionOperationMaterials { get; set; }
        public virtual DbSet<ProductionOperation> ProductionOperations { get; set; }
        public virtual DbSet<ProductionOrderOperation> ProductionOrderOperations { get; set; }
        public virtual DbSet<ProductionOrder> ProductionOrders { get; set; }
        public virtual DbSet<PurchaseOrderItem> PurchaseOrderItems { get; set; }
        public virtual DbSet<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual DbSet<SalesOrderItemBatch> SalesOrderItemBatches { get; set; }
        public virtual DbSet<SalesOrderItem> SalesOrderItems { get; set; }
        public virtual DbSet<SalesOrder> SalesOrders { get; set; }
        public virtual DbSet<SupplierAddress> SupplierAddresses { get; set; }
        public virtual DbSet<SupplierContact> SupplierContacts { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
    }
}
