//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bluephase.Data.EF6.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentVersion
    {
        public DocumentVersion()
        {
            this.DocumentAudits = new HashSet<DocumentAudit>();
        }
    
        public int DocumentVersionId { get; set; }
        public int DocumentId { get; set; }
        public System.Guid UniqueName { get; set; }
        public byte[] SHA1Hash { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual ICollection<DocumentAudit> DocumentAudits { get; set; }
        public virtual Document Document { get; set; }
    }
}
