//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bluephase.Data.EF6.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentAudit
    {
        public int DocumentAuditId { get; set; }
        public int DocumentVersionId { get; set; }
        public string Action { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual DocumentVersion DocumentVersion { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
