//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bluephase.Data.EF6.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeGroup
    {
        public EmployeeGroup()
        {
            this.Employees = new HashSet<Employee>();
        }
    
        public int EmployeeGroupId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public byte[] Permissions { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    
        public virtual EmployeeGroup EmployeeGroups1 { get; set; }
        public virtual EmployeeGroup EmployeeGroup1 { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
