//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bluephase.Data.EF6.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public Material()
        {
            this.MaterialSuppliers = new HashSet<MaterialSupplier>();
            this.PartVersionMaterials = new HashSet<PartVersionMaterial>();
            this.ProductionOperationMaterials = new HashSet<ProductionOperationMaterial>();
            this.PurchaseOrderItems = new HashSet<PurchaseOrderItem>();
        }
    
        public int MaterialId { get; set; }
        public string Name { get; set; }
        public int MaterialFormId { get; set; }
        public Nullable<double> MinStockLevel { get; set; }
        public Nullable<double> MaxStockLevel { get; set; }
        public string UnitOfMeasurement { get; set; }
        public byte[] ImageBytes { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    
        public virtual MaterialForm MaterialForm { get; set; }
        public virtual ICollection<MaterialSupplier> MaterialSuppliers { get; set; }
        public virtual ICollection<PartVersionMaterial> PartVersionMaterials { get; set; }
        public virtual ICollection<ProductionOperationMaterial> ProductionOperationMaterials { get; set; }
        public virtual ICollection<PurchaseOrderItem> PurchaseOrderItems { get; set; }
    }
}
