//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bluephase.Data.EF6.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialSupplier
    {
        public int MaterialId { get; set; }
        public int SupplierId { get; set; }
        public int SupplierContactId { get; set; }
        public System.DateTime TenderDate { get; set; }
        public decimal Cost { get; set; }
        public double CostPer { get; set; }
        public int LeadTimeInDays { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
