//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bluephase.Data.EF6.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartVersion
    {
        public PartVersion()
        {
            this.NonConformancies = new HashSet<NonConformancy>();
            this.PartVersionDocuments = new HashSet<PartVersionDocument>();
            this.PartVersionMaterials = new HashSet<PartVersionMaterial>();
            this.ProductionOperations = new HashSet<ProductionOperation>();
            this.SalesOrderItems = new HashSet<SalesOrderItem>();
        }
    
        public int PartVersionId { get; set; }
        public int PartId { get; set; }
        public string VersionNumber { get; set; }
        public byte[] ImageBytes { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    
        public virtual ICollection<NonConformancy> NonConformancies { get; set; }
        public virtual Part Part { get; set; }
        public virtual ICollection<PartVersionDocument> PartVersionDocuments { get; set; }
        public virtual ICollection<PartVersionMaterial> PartVersionMaterials { get; set; }
        public virtual ICollection<ProductionOperation> ProductionOperations { get; set; }
        public virtual ICollection<SalesOrderItem> SalesOrderItems { get; set; }
    }
}
