//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bluephase.Data.EF6.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.CustomerContacts = new HashSet<CustomerContact>();
            this.NonConformancies = new HashSet<NonConformancy>();
            this.NonConformancies1 = new HashSet<NonConformancy>();
            this.PersonAddresses = new HashSet<PersonAddress>();
            this.PersonContactDetails = new HashSet<PersonContactDetail>();
            this.PurchaseOrders = new HashSet<PurchaseOrder>();
            this.SalesOrders = new HashSet<SalesOrder>();
            this.SupplierContacts = new HashSet<SupplierContact>();
        }
    
        public int PersonId { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Suffix { get; set; }
        public string NickName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    
        public virtual ICollection<CustomerContact> CustomerContacts { get; set; }
        public virtual ICollection<NonConformancy> NonConformancies { get; set; }
        public virtual ICollection<NonConformancy> NonConformancies1 { get; set; }
        public virtual ICollection<PersonAddress> PersonAddresses { get; set; }
        public virtual ICollection<PersonContactDetail> PersonContactDetails { get; set; }
        public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual ICollection<SalesOrder> SalesOrders { get; set; }
        public virtual ICollection<SupplierContact> SupplierContacts { get; set; }
    }
}
