//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bluephase.Data.EF6.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionOrder
    {
        public ProductionOrder()
        {
            this.ProductionOrderOperations = new HashSet<ProductionOrderOperation>();
            this.PurchaseOrderItems = new HashSet<PurchaseOrderItem>();
        }
    
        public int ProductionOrderId { get; set; }
        public int SalesOrderItemId { get; set; }
        public string InternalReference { get; set; }
        public string Status { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    
        public virtual ICollection<ProductionOrderOperation> ProductionOrderOperations { get; set; }
        public virtual SalesOrderItem SalesOrderItem { get; set; }
        public virtual ICollection<PurchaseOrderItem> PurchaseOrderItems { get; set; }
    }
}
