//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bluephase.Data.EF6.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrderItem
    {
        public SalesOrderItem()
        {
            this.NonConformancies = new HashSet<NonConformancy>();
            this.ProductionOrders = new HashSet<ProductionOrder>();
            this.SalesOrderItemBatches = new HashSet<SalesOrderItemBatch>();
        }
    
        public int SalesOrderItemId { get; set; }
        public int SalesOrderId { get; set; }
        public string CustomerOrderItemNumber { get; set; }
        public int PartVersionId { get; set; }
        public int TotalQuantity { get; set; }
        public string Status { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    
        public virtual ICollection<NonConformancy> NonConformancies { get; set; }
        public virtual PartVersion PartVersion { get; set; }
        public virtual ICollection<ProductionOrder> ProductionOrders { get; set; }
        public virtual ICollection<SalesOrderItemBatch> SalesOrderItemBatches { get; set; }
        public virtual SalesOrder SalesOrder { get; set; }
    }
}
