//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bluephase.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.CustomerAddresses = new HashSet<CustomerAddress>();
            this.CustomerContacts = new HashSet<CustomerContact>();
            this.Parts = new HashSet<Part>();
            this.SalesOrders = new HashSet<SalesOrder>();
        }
    
        public int CustomerId { get; set; }
        public string Name { get; set; }
        public string Terms { get; set; }
        public string VATNumber { get; set; }
        public bool Approved { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    
        public virtual ICollection<CustomerAddress> CustomerAddresses { get; set; }
        public virtual ICollection<CustomerContact> CustomerContacts { get; set; }
        public virtual ICollection<Part> Parts { get; set; }
        public virtual ICollection<SalesOrder> SalesOrders { get; set; }
    }
}
