//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bluephase.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public Document()
        {
            this.DocumentVersions = new HashSet<DocumentVersion>();
            this.PartDocuments = new HashSet<PartDocument>();
            this.PartVersionDocuments = new HashSet<PartVersionDocument>();
            this.ProductionOperationDocuments = new HashSet<ProductionOperationDocument>();
        }
    
        public int DocumentId { get; set; }
        public string FileName { get; set; }
        public int DocumentTypeId { get; set; }
        public bool IsApproved { get; set; }
        public byte[] PermissionsBytes { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    
        public virtual DocumentType DocumentType { get; set; }
        public virtual ICollection<DocumentVersion> DocumentVersions { get; set; }
        public virtual ICollection<PartDocument> PartDocuments { get; set; }
        public virtual ICollection<PartVersionDocument> PartVersionDocuments { get; set; }
        public virtual ICollection<ProductionOperationDocument> ProductionOperationDocuments { get; set; }
    }
}
