//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bluephase.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Part
    {
        public Part()
        {
            this.PartDocuments = new HashSet<PartDocument>();
            this.Parts1 = new HashSet<Part>();
            this.PartVersions = new HashSet<PartVersion>();
        }
    
        public int PartId { get; set; }
        public int CustomerId { get; set; }
        public string DrawingNumber { get; set; }
        public string Name { get; set; }
        public Nullable<int> AssemblyPartId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<PartDocument> PartDocuments { get; set; }
        public virtual ICollection<Part> Parts1 { get; set; }
        public virtual Part Part1 { get; set; }
        public virtual ICollection<PartVersion> PartVersions { get; set; }
    }
}
