//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bluephase.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionOrderOperation
    {
        public int ProductionOrderOperationId { get; set; }
        public int ProductionOrderId { get; set; }
        public int ProductionOperationId { get; set; }
        public int QuantityFinished { get; set; }
        public int ActualProductionCentreId { get; set; }
        public double ActualSetupTime { get; set; }
        public double ActualCycleTime { get; set; }
        public string Status { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    
        public virtual ProductionCentre ProductionCentre { get; set; }
        public virtual ProductionOperation ProductionOperation { get; set; }
        public virtual ProductionOrder ProductionOrder { get; set; }
    }
}
