//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bluephase.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionOperation
    {
        public ProductionOperation()
        {
            this.ProductionOperationDocuments = new HashSet<ProductionOperationDocument>();
            this.ProductionOperationMaterials = new HashSet<ProductionOperationMaterial>();
            this.ProductionOrderOperations = new HashSet<ProductionOrderOperation>();
        }
    
        public int ProductionOperationId { get; set; }
        public int PartVersionId { get; set; }
        public int Sequence { get; set; }
        public Nullable<double> SetupTime { get; set; }
        public Nullable<double> CycleTime { get; set; }
        public int ProductionCentreId { get; set; }
        public int CostUpliftPercentage { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string Description { get; set; }
    
        public virtual PartVersion PartVersion { get; set; }
        public virtual ProductionCentre ProductionCentre { get; set; }
        public virtual ICollection<ProductionOperationDocument> ProductionOperationDocuments { get; set; }
        public virtual ICollection<ProductionOperationMaterial> ProductionOperationMaterials { get; set; }
        public virtual ICollection<ProductionOrderOperation> ProductionOrderOperations { get; set; }
    }
}
