//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bluephase.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrder
    {
        public SalesOrder()
        {
            this.SalesOrderItems = new HashSet<SalesOrderItem>();
        }
    
        public int SalesOrderId { get; set; }
        public int CustomerId { get; set; }
        public string OrderNumber { get; set; }
        public System.DateTime ReceivedDate { get; set; }
        public int PersonId { get; set; }
        public bool HasBeenAcknowledged { get; set; }
        public bool HasBeenApproved { get; set; }
        public string Status { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Person Person { get; set; }
        public virtual ICollection<SalesOrderItem> SalesOrderItems { get; set; }
    }
}
