//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bluephase.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public Supplier()
        {
            this.MaterialSuppliers = new HashSet<MaterialSupplier>();
            this.PurchaseOrders = new HashSet<PurchaseOrder>();
            this.SupplierAddresses = new HashSet<SupplierAddress>();
            this.SupplierContacts = new HashSet<SupplierContact>();
        }
    
        public int SupplierId { get; set; }
        public string Name { get; set; }
        public string Terms { get; set; }
        public bool IsApproved { get; set; }
        public System.DateTime ApprovedDate { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    
        public virtual ICollection<MaterialSupplier> MaterialSuppliers { get; set; }
        public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual ICollection<SupplierAddress> SupplierAddresses { get; set; }
        public virtual ICollection<SupplierContact> SupplierContacts { get; set; }
    }
}
